language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - PACKAGE="mirage-logs"
   - REVDEPS="true"
 matrix:
   - DISTRO=alpine OCAML_VERSION=4.06
   - DISTRO=alpine OCAML_VERSION=4.07
   - DISTRO=alpine OCAML_VERSION=4.08
   - DISTRO=alpine OCAML_VERSION=4.09
